[workspace]
resolver = "2"
members = [
    "package",
    "tests",
    "bench",
]

[workspace.dependencies]
async-std = "^1.13.0"

[workspace.dependencies.filego]
path = "./package"
features = ["all"]
