[package]
name = "filego"
version = "0.2.0"
authors = ["Alpheus Tang"]
edition = "2021"
description = """
A solution for splitting, checking and merging files
"""
readme = "README.md"
homepage = "https://github.com/alpheustangs/filego-rust"
repository = "https://github.com/alpheustangs/filego-rust"
license = "MIT"
keywords = [
    "split",
    "check",
    "merge",
    "util",
    "fs",
]
categories = [
    "filesystem",
]
include = [
    "src/*", 
    "Cargo.toml", 
    "README.md",
]

[lib]
name = "filego"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.38.0", features = ["fs", "io-util"] }
